mycash/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

# All url that system use in this Web Page
app_name = 'mycash'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),                                        # /mycash/
    url(r'^sign-in/', views.SignInView.as_view(), name='sign-in'),                              # /mycash/sign_in/
    url(r'^sign-up/', views.SignUpView.as_view(), name='sign-up'),                              # /mycash/sign_up/

    url(r'^log-out/', login_required(views.LogOutView.as_view()), name='log-out'),
    url(r'^del-account/', login_required(views.MyUserDeleteView.as_view()), name='del-account'),
    url(r'^profile/', login_required(views.ProfileView.as_view()), name='profile'),                             # /mycash/profile/
    url(r'^upd-user/(?P<pk>\d+)/$', login_required(views.UserUpdate.as_view()), name='upd-user'),    # /mycash/profile-edit
    url(r'^overview/', login_required(views.CategoryIndexView.as_view()), name='overview'),                     # /mycash/overview/
    url(r'^detail/(?P<pk>[0-9]+)/$', login_required(views.CategoryDetailView.as_view()), name='detail'),        # /mycash/income/<pk>/

    url(r'^add-income/', login_required(views.IncomeCreate.as_view()), name='add-income'),                      # /mycash/add_income/
    url(r'^upd-income/(?P<pk>\d+)/$', login_required(views.IncomeUpdate.as_view()), name='upd-income'),         # /mycash/upd_income/
    url(r'^del-income/(?P<pk>\d+)/$', login_required(views.IncomeDelete.as_view()), name='del-income'),         # /mycash/upd_expense/

    url(r'^add-expense/', login_required(views.ExpenseCreate.as_view()), name='add-expense'),                   # /mycash/add_expense/
    url(r'^upd-expense/(?P<pk>\d+)/$', login_required(views.ExpenseUpdate.as_view()), name='upd-expense'),      # /mycash/upd_expense/
    url(r'^del-expense/(?P<pk>\d+)/$', login_required(views.ExpenseDelete.as_view()), name='del-expense'),      # /mycash/del_expense/

    url(r'^add-category/', login_required(views.CategoryCreate.as_view()), name='add-category'),                    # /mycash/add_category/
    url(r'^upd-category/(?P<pk>[0-9]+)/$', login_required(views.CategoryUpdate.as_view()), name='upd-category'),    # /mycash/uod_category/
    url(r'^del-category/(?P<pk>[0-9]+)/$', login_required(views.CategoryDelete.as_view()), name='del-category'),    # /mycash/del_category/

    url(r'^send-technical/', login_required(views.TechnicalRequestCreate.as_view()), name='send-technical'),                # /mycash/send-technical/

    url(r'^goal/', login_required(views.GoalView.as_view()), name='goal'),                              # /mycash/goal
    url(r'^add-goal/', login_required(views.GoalCreate.as_view()), name='add-goal'),                    # /mycash/add_goal/
    url(r'^upd-goal/(?P<pk>[0-9]+)/$', login_required(views.GoalUpdate.as_view()), name='upd-goal'),    # /mycash/uod_goal/
    url(r'^del-goal/(?P<pk>[0-9]+)/$', login_required(views.GoalDelete.as_view()), name='del-goal'),    # /mycash/del_delete/

    url(r'^expense/', login_required(views.ExpenseIndexView.as_view()), name='expense'),                # /mycash/expense/
    url(r'^income/', login_required(views.IncomeIndexView.as_view()), name='income'),                   # /mycash/income/

    url(r'^chart/', login_required(views.ChartView.as_view()), name='chart'),                            # /mycash/chart/
    url(r'^api/chart/data', login_required(views.ChartData.as_view()), name='chart-data'),               # /mycash/api/chart/data/

    url(r'^pdf/', login_required(views.GeneratePDF.as_view()), name='pdf'),
    url(r'^historical/', login_required(views.HistoricalView.as_view()), name='historical'),
    url(r'^api/historical/data/', login_required(views.HistoricalData.as_view()), name='historical-data'),

    url(r'^add-cat/', login_required(views.CatCreate.as_view()), name='add-cat'),
]

sgpf/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),           
    url(r'^mycash/', include('mycash.urls'))   ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mycash/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core.validators import MinValueValidator, RegexValidator
from django.core.urlresolvers import reverse
from datetime import datetime
from django.utils import timezone
from django.db import models

"""
    Mapping of the classes described below, all these are converted into tables 
    in the database, and in case complementary tables can be created for relationships 
    that have.
"""


# class controller MyUser create
class PerBaseUserManager(BaseUserManager):
    def create_user(self, email, password):
        user = self.model(email=email)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(email, password)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


# MyUser class [User]
class MyUser(AbstractBaseUser, PermissionsMixin):
    email = models.CharField(max_length=50, unique=True)  # user email
    nickname = models.CharField(max_length=20, validators=[
        RegexValidator(regex='^[\w\s]*$', message='Nickname must be Alphanumeric', code='invalid_nickname')])

    name = models.CharField(max_length=30, validators=[
        RegexValidator(regex='^[a-zA-Z\s]*$', message='Name must be Alphabetic', code='invalid_name')])

    last_name = models.CharField(max_length=50, validators=[
        RegexValidator(regex='^[a-zA-Z\s]*$', message='Name must be Alphabetic', code='invalid_last_name')])

    phone = models.CharField(max_length=12, validators=[
        RegexValidator(regex='^[0-9]*$', message='Nickname must be Numeric', code='invalid_phone')])        # user phone

    description = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    objects = PerBaseUserManager()

    def get_full_name(self):
        cad = "{0} {1}"
        return cad.format(self.name, self.last_name)

    def get_short_name(self):
        return self.nickname

    def __str__(self):  # print
        cad = "{0} {1}, {2}"
        return cad.format(self.name, self.last_name, self.email)


# Category class that will be mapped in the database as a table. [mycash_category]
class Category(models.Model):
    name = models.CharField(max_length=30, validators=[
        RegexValidator(regex='^[a-zA-Z]*$', message='Name must be Alphabetic', code='invalid_name')])
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    create_on = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('mycash:detail', kwargs={'pk': self.pk})

    @classmethod
    def create(cls, name, user):
        category = cls(name=name, user=user)
        return category

    def __str__(self):
        return self.name


# Income class that will be mapped in the database as a table. [mycash_income]
class Income(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=8, decimal_places=2, validators=[MinValueValidator(0.001)])
    name = models.CharField(max_length=20, validators=[
        RegexValidator(regex='^[\w\s]*$', message='Name must be Alphanumeric', code='invalid_name'),
    ])
    date = models.DateField(default=datetime.now)

    def get_income(self):
        return self.recipephotos_set.filter(type="3")


# Expense class that will be mapped in the database as a table. [mycash_expense]
class Expense(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=8, decimal_places=2, validators=[MinValueValidator(0.001)])
    name = models.CharField(max_length=20, validators=[
        RegexValidator(regex='^[\w\s]*$', message='Name must be Alphanumeric', code='invalid_name'),
    ])
    date = models.DateField(default=datetime.now)


class TechnicalRequest(models.Model):
    description = models.TextField(blank=True, null=True)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    state = models.BooleanField(default=False)
    send_on = models.DateField(default=datetime.now)


# Goal class
class Goal(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, validators=[
        RegexValidator(regex='^[\w\s]*$', message='Name must be Alphanumeric', code='invalid_name'),
    ])
    percentage = models.DecimalField(max_digits=4, decimal_places=2, validators=[MinValueValidator(0.1)])
    adv_percentage = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    amount = models.DecimalField(max_digits=14, decimal_places=2, validators=[MinValueValidator(0.001)])

mycash/forms.py
from django import forms
from .models import Income, Expense, MyUser, Category, TechnicalRequest, Goal
from django.contrib.auth.forms import UserChangeForm

""" 
    creation of the ModelForm forms, this is super useful to update,
    delete and insert records in their respective models
    
        [CRUD] View 
            Create View
            Retrieve View
            Update View
            Delete View
"""


class DateInput(forms.DateInput):
    input_type = 'date'


class MyUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = MyUser
        fields = ['name', 'last_name', 'email', 'password']

        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name', 'class': 'form-control'}),           # name field of Class User
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name', 'class': 'form-control'}),      # last_name field of Class User
            'email': forms.TextInput(attrs={'placeholder': 'Email', 'class': 'form-control'}),          # email field of Class User
        }

    def clean_email(self):
        email = self.cleaned_data.get('email')

        t = False
        for c in email:
            if c == '@':
                t = True

        if t:
            email_base, provider = email.split('@')
            if not provider == 'mycash.com':
                raise forms.ValidationError("Please make sure you use your @mycash.com email.")
            return email
        else:
            raise forms.ValidationError("Need to enter @mycash.com!!")


# Class UserForm, Use to Create Model User [Objects]data_attrs=('slug',),
class MyUserUpdateForm(UserChangeForm):
    class Meta:
        model = MyUser
        fields = ['name', 'last_name', 'nickname', 'phone', 'description', 'password']

        # The fields present in the form
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name', 'class': 'form-control'}),           # name field of Class User
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name', 'class': 'form-control'}),      # last_name field of Class User
            'nickname': forms.TextInput(attrs={'placeholder': 'Nickname', 'class': 'form-control'}),       # name field of Class User
            'phone': forms.TextInput(attrs={'placeholder': 'Phone', 'class': 'form-control'}),          # phone field of Class User
            'description': forms.Textarea(attrs={'class': 'form-control', 'cols': 20, 'rows': 3}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),          # phone field of Class User
        }


# Only form, to capture the data, through POST-GET methods
# It does not represent a model
class SignInForm(forms.Form):
    email = forms.CharField(required=True, label='Email',
                            widget=(forms.TextInput(attrs={'placeholder': 'Email', 'class': 'form-control'})))
    password = forms.CharField(required=True, label='Password',
                               widget=(forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control'})))


class DeleteForm(forms.Form):
    password1 = forms.CharField(required=True, label='Password',
                            widget=(forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control'})))
    password2 = forms.CharField(required=True, label='Confirm Password',
                            widget=(forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control'})))


# Class IncomeForm, Use to Create Model Income [Objects]
class IncomeForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = ['name', 'amount', 'date', 'category']

        # The fields present in the form
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),           # name field of Class Income
            'amount': forms.TextInput(attrs={'class': 'form-control'}),         # amount field of Class Income
            'date': DateInput(attrs={'class': 'form-control'}),         # amount field of Class Income
            'category': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, user, *args, **kwargs):
        super(IncomeForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.filter(user=user)


# Class ExpenseForm, Use to Create Model Expense [Objects]
class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['name', 'amount', 'date', 'category']

        # The fields present in the form
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),           # name field of Class Expense
            'amount': forms.TextInput(attrs={'class': 'form-control'}),         # amount field of Class Expense
            'date': DateInput(attrs={'class': 'form-control'}),         # amount field of Class Income
            'category': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, user, *args, **kwargs):
        super(ExpenseForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.filter(user=user)


# Class IncomeForm, Use to Create Model Income [Objects]
class IncomeUpdateForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = ['name', 'amount', 'date']

        # The fields present in the form
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),           # name field of Class Income
            'amount': forms.TextInput(attrs={'class': 'form-control'}),         # amount field of Class Income
            'date': DateInput(attrs={'class': 'form-control'}),         # amount field of Class Income
        }


# Class ExpenseForm, Use to Create Model Expense [Objects]
class ExpenseUpdateForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['name', 'amount', 'date']

        # The fields present in the form
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),           # name field of Class Expense
            'amount': forms.TextInput(attrs={'class': 'form-control'}),         # amount field of Class Expense
            'date': DateInput(attrs={'class': 'form-control'}),         # amount field of Class Income
        }


# Class ExpenseForm, Use to Create Model Expense [Objects]
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

        # The fields present in the form
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),  # name field of Class Expense
        }


class TechnicalRequestForm(forms.ModelForm):
    class Meta:
        model = TechnicalRequest
        fields = ['description']

        # The fields present in the form
        widgets = {
            'description': forms.Textarea(attrs={'class': 'form-control', 'cols': 50, 'rows': 15}),  # name field of Class Expense
        }


# Class ExpenseForm, Use to Create Model Expense [Objects]
class GoalForm(forms.ModelForm):
    class Meta:
        model = Goal
        fields = ['name', 'percentage', 'amount']

        # The fields present in the form
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),           # name field of Class Goal
            'percentage': forms.TextInput(attrs={'class': 'form-control'}),     # percentage field of Class Goal
            'amount': forms.TextInput(attrs={'class': 'form-control'}),         # amount field of Class Goal
        }

mycash/templates/mycash/button.html
<!-- Modal -->

<!-- Trigger the modal with a button -->
<div>
    <div class="pull-left" >
        <div class="btn-group">
            <button onclick="return open_modal('{% url 'mycash:add-category' %}')" type="button" class="btn btn-primary">Add Category</button>
            <a href="{% url 'mycash:add-income' %}" class="btn btn-primary" role="button">Add Income</a>
            <a href="{% url 'mycash:add-expense' %}" class="btn btn-primary" role="button">Add Expense</a>
            <button onclick="return open_modal('{% url 'mycash:add-goal' %}')" type="button" class="btn btn-primary">Add Goal</button>
            <button onclick="return open_modal('{% url 'mycash:goal' %}')" type="button" class="btn btn-primary">Show Goals</button>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Chart Information</button>

            <!-- Modal -->
            <div class="modal fade" id="myModal" role="dialog">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Graphics</h4>
                        </div>

                        <div class="modal-body">
                            <h5>Income-Expense Chart</h5>
                            <p>The graph of the left represents the Income for months, the X axis is the eses and the Y the amount won. </p>
                            <hr>
                            <h5>Incomes</h5>
                            <p>The graph on the right, similar to the left, but this is given between days, since expenditures are given daily.</p>
                            <hr>
                            <h5>Expenses</h5>
                            <p>You can change the type of graphic, it is still very static, but we are working on it. [d3.js]</p>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-basic" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pull-right">
        <form name="chart" method="GET">
            <select name="type_chart" onchange="typeChart(this);" class="btn btn-primary">
                <option value="bar">Bar</option>
                <option value="line">Line</option>
                <option value="horizontalBar">Horizontal</option>
                <option value="polarArea">Polar</option>
                <option value="radar">Radar</option>
            </select>
        </form>
    </div>
    <div class="clearfix"></div>
</div>
<br>

<div id="popup" class="modal fade" role="dialog">   </div>

<script>
    function open_modal(url){
        $('#popup').load(url, function(){
            $(this).modal('show');
        });
        return false;
    }

    function close_modal(){
        $('#popup').modal('hide');
        return false;
    }
</script>

mycash/templates/mycash/detail.html
{% extends 'mycash/base.html' %}
{% block title %}Income/Expense Details{% endblock %}

<!--
    Detailed view of income and expenses by category,
    shows all records both expenses and income.
    For each record we are allowed to edit this data and enter data.
-->

{% block body %}
    <h1 class="text-center text-success">{{ category.name }}</h1>

    <div class="col-sm-12">
        <!-- Income Details Table -->
        <div class="col-sm-6">
            <h2 class="text-center text-primary"><strong>Incomes</strong></h2>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <th scope="col">#</th>
                        <th scope="col">Income</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Date</th>
                        <th scope="col">Edit</th>
                        <th scope="col">Delete</th>
                    </thead>
                    <tbody>
                        {% for income in category.income_set.all|dictsortreversed:"date"|slice:":8" %}
                            <tr>
                                <th>{{ forloop.counter }}</th>
                                <td>{{ income.name }}</td>
                                <td>{{ income.amount }}</td>
                                <td>{{ income.date }}</td>
                                <td><a href="{% url 'mycash:upd-income' income.id %}"><i class="glyphicon glyphicon-edit"></i></a></td>
                                <td>
                                    <form action="{% url 'mycash:del-income' income.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden", name="income_id" value="{{ income.id }}">
                                        <button type="submit" class="btn btn-danger btn-sm">
                                            <span class="glyphicon glyphicon-trash"></span>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Expense Details Table -->
        <div class="col-sm-6">
            <h2 class="text-center text-danger"><strong>Expenses</strong></h2>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <th scope="col">#</th>
                        <th scope="col">Expense</th>
                        <th scope="col">Amount</th>
                        <th scope="col">Date</th>
                        <th scope="col">Edit</th>
                        <th scope="col">Delete</th>
                    </thead>
                    <tbody>
                        {% for expense in category.expense_set.all|dictsortreversed:"date"|slice:":8" %}
                            <tr>
                                <th>{{ forloop.counter }}</th>
                                <td>{{ expense.name }}</td>
                                <td>{{ expense.amount }}</td>
                                <td>{{ expense.date }}</td>
                                <td><a href="{% url 'mycash:upd-expense' expense.id %}"><i class="glyphicon glyphicon-edit"></i></a></td>
                                <td>
                                    <form action="{% url 'mycash:del-expense' expense.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden", name="expense_id" value="{{ expense.id }}">
                                        <button type="submit" class="btn btn-danger btn-sm">
                                            <span class="glyphicon glyphicon-trash"></span>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

mycash/templates/mycash/expense.html
{% extends 'mycash/base.html' %}
{% block title %}Expense Details{% endblock %}

{% block body %}
<h2 align="center" class="text-success fa-2x">Expenses Total: {{ texpense.amount__sum }}</h2>

<div>
    <div class="pull-left" >
        <div class="btn-group">
            <a href="{% url 'mycash:add-expense' %}" class="btn btn-primary" role="button">Add Expense</a>
        </div>
    </div>
    <div class="pull-right">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
            <i class="fa fa-folder"></i> Information
        </button>
    </div>
    <div class="clearfix"></div>
</div>

<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Expense Data</h4>
            </div>

            <div class="modal-body">
                <h5>Entered Expense</h5>
                <p>List of all expense, from the first to the last one entered, ordered by the date of entry</p>
                <hr>
                <h5>Search</h5>
                <p>Functionality to search for an expense by name, date or both, return those containing the text boxes.</p>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-basic" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<br><br>
{% include "mycash/search.html" %}

<div class="table-responsive">
    <table class="table table-striped" >
        <thead>
            <th scope="col">#</th>
            <th scope="col">Expense</th>
            <th scope="col">Amount</th>
            <th scope="col">Date</th>
            <th scope="col">Update</th>
            <th scope="col">Delete</th>
        </thead>
        <tbody>
            {% for expense in all_expense %}
                <tr>
                    <th>{{ forloop.counter }}</th>
                    <td>{{ expense.name }}</td>
                    <td>{{ expense.amount }}</td>
                    <td>{{ expense.date }}</td>
                    <td><a href="{% url 'mycash:upd-expense' expense.id %}"><i class="glyphicon glyphicon-edit"></i></a></td>
                    <td>
                        <form action="{% url 'mycash:del-expense' expense.id %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden", name="expense_id" value="{{ expense.id }}">
                            <button type="submit" class="btn btn-danger btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% if is_paginated %}
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
        <li class="disabled"><span>&laquo;</span></li>
    {% endif %}

    {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
            <li><a href="?page={{ i }}&name={{ request.GET.name }}&date={{ request.GET.date }}">{{ i }}</a></li>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
        <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
</ul>
{% endif %}

{% endblock %}

mycash/templates/mycash/index.html
<!--
    Main view of the page, is the first thing we see when entering our website
        Sign-In
        Sign-Up
-->

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load staticfiles %}
    <link rel="icon" type="image/png" href="{% static 'mycash/images/favicon.png' %}">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"	>
    <link rel="stylesheet" href="{% static 'mycash/css/index.css'  %}" type="text/css"/>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<title>MyCash</title>
</head>

<body>
	<div class="container-full">

		<!-- Nav -->
		<nav class="navbar navbar-inverse navbar-static-top">
			<div class="container margin-left-nav">
				<div class="row">
					<div class="col-md-2">
						<!-- Navbar brand (Brainiac) y botón colapsable -->
						<div class="navbar-header">
							<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                          </button>
							<a class="navbar-brand" href="{% url 'mycash:index' %}">MyCash</a>
						</div>
					</div>

					<div class="col-md-10">
						<div class="navbar-collapse collapse" id="navbar-main">

							<!-- Navbar botones -->
                            <ul class="nav navbar-nav navbar-right horizontal">
								<li><a href="{% url 'mycash:sign-in' %}"><i class="glyphicon glyphicon-log-in"></i>  Sign In</a></li>
							</ul>
                            <ul class="nav navbar-nav navbar-right horizontal">
								<li><a href="{% url 'mycash:sign-up' %}"><i class="glyphicon glyphicon-user"></i>  Sign Up</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</nav>
	</div>

    {% block body %}
    {% endblock %}
    <footer>
      <p>MyCash [Cerpa - Mamani -Maldonado - Zevallos]</p>
    </footer>
</body>
</html>

mycash/templates/mycash/sign-up.html
{% extends 'mycash/index.html' %}

<!--
    UserForm Created in the forms, this based on ModelForm, what it does is map the
    fields with the attributes of the class, and thus save it, update it and
    delete it.
        [CRUD]
-->

{% block body%}

<div class="col-sm-12">
    <div class="col-sm-6">
        <br>
        <div class="login-form">
            <form method="post">
                <h4 class="modal-title">Create Your Account</h4>

                {% csrf_token %}
                {% include 'mycash/form-template.html' %}

                <input type="submit" class="btn btn-primary btn-block btn-lg" value="Sign Up">
            </form>
            <div class="text-center small">Do you have an account? <a href="{% url 'mycash:sign-in' %}">Sign In</a></div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="icon-img">
            <img src="../../static/mycash/images/icon.png" width="90%">
        </div>
    </div>
</div>
{% endblock %}